#!/usr/bin/env python3
"""
Database management CLI for DevOps Incident Support Model.

Run from the ``backend/`` directory:

    python scripts/db.py <command> [options]

Commands
--------
migrate          Apply all pending migrations (alembic upgrade head).
rollback         Revert the last migration (alembic downgrade -1).
downgrade <rev>  Downgrade to a specific revision (e.g. ``base``).
reset            Downgrade to base, then re-apply all migrations.
seed             Populate the database with default data (roles).
current          Print the current migration revision.
history          Print the migration history.
create-migration Create a new autogenerated migration file.
check            Verify the database matches the latest migration.
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Ensure ``backend/`` is on sys.path when the script is run directly.
# ---------------------------------------------------------------------------
_BACKEND_DIR = Path(__file__).resolve().parent.parent
if str(_BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(_BACKEND_DIR))

# Must import after path setup
from alembic import command as alembic_command  # noqa: E402
from alembic.config import Config as AlembicConfig  # noqa: E402

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)


# ---------------------------------------------------------------------------
# Alembic config helper
# ---------------------------------------------------------------------------


def _get_alembic_cfg() -> AlembicConfig:
    """
    Build an Alembic ``Config`` pointing at ``alembic.ini`` in ``backend/``.

    Returns:
        A configured :class:`alembic.config.Config` instance.
    """
    ini_path = _BACKEND_DIR / "alembic.ini"
    if not ini_path.exists():
        logger.error("alembic.ini not found at %s", ini_path)
        sys.exit(1)
    return AlembicConfig(str(ini_path))


# ---------------------------------------------------------------------------
# Command handlers
# ---------------------------------------------------------------------------


def cmd_migrate(args: argparse.Namespace) -> None:
    """Apply all pending migrations (upgrade to head)."""
    logger.info("Applying all pending migrations...")
    alembic_command.upgrade(_get_alembic_cfg(), "head")
    logger.info("Done — database is at head.")


def cmd_rollback(args: argparse.Namespace) -> None:
    """Revert the most recent migration."""
    logger.info("Reverting the last migration (-1)...")
    alembic_command.downgrade(_get_alembic_cfg(), "-1")
    logger.info("Done — rolled back one revision.")


def cmd_downgrade(args: argparse.Namespace) -> None:
    """Downgrade to a specific revision."""
    target = args.revision
    logger.info("Downgrading to revision '%s'...", target)
    alembic_command.downgrade(_get_alembic_cfg(), target)
    logger.info("Done — database downgraded to '%s'.", target)


def cmd_reset(args: argparse.Namespace) -> None:
    """Downgrade to base then re-apply all migrations."""
    logger.warning("RESET: This will drop and recreate all tables.")
    alembic_command.downgrade(_get_alembic_cfg(), "base")
    logger.info("Downgraded to base — re-applying all migrations...")
    alembic_command.upgrade(_get_alembic_cfg(), "head")
    logger.info("Done — database reset complete.")


def cmd_seed(args: argparse.Namespace) -> None:
    """Seed the database with default application data."""
    logger.info("Running database seed...")
    from app.database.seed import run as run_seed  # noqa: PLC0415

    run_seed()


def cmd_current(args: argparse.Namespace) -> None:
    """Print the current migration revision."""
    alembic_command.current(_get_alembic_cfg(), verbose=True)


def cmd_history(args: argparse.Namespace) -> None:
    """Print the full migration history."""
    alembic_command.history(_get_alembic_cfg(), verbose=True)


def cmd_create_migration(args: argparse.Namespace) -> None:
    """Generate a new autogenerated migration file."""
    message: str = args.message
    if not message:
        logger.error("A migration message is required: -m 'describe the change'")
        sys.exit(1)
    logger.info("Generating migration: '%s'", message)
    alembic_command.revision(
        _get_alembic_cfg(),
        message=message,
        autogenerate=True,
    )
    logger.info("Migration file created in alembic/versions/")


def cmd_check(args: argparse.Namespace) -> None:
    """
    Verify the live database matches the current migration head.

    Exits with code 1 if migrations are pending.
    """
    logger.info("Checking migration status...")
    alembic_command.check(_get_alembic_cfg())
    logger.info("OK — database schema is up to date.")


# ---------------------------------------------------------------------------
# Argument parser
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="db.py",
        description="DevOps Incident Support Model — database management CLI.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    subparsers = parser.add_subparsers(dest="command", metavar="<command>")
    subparsers.required = True

    # migrate
    subparsers.add_parser("migrate", help="Apply all pending migrations.")

    # rollback
    subparsers.add_parser("rollback", help="Revert the last migration.")

    # downgrade
    dg = subparsers.add_parser("downgrade", help="Downgrade to a specific revision.")
    dg.add_argument(
        "revision",
        help="Target revision (e.g. 'base', '-1', '8a4b2c3d4ef0').",
    )

    # reset
    subparsers.add_parser(
        "reset",
        help="Downgrade to base then re-apply all migrations (destructive!).",
    )

    # seed
    subparsers.add_parser("seed", help="Seed default application data.")

    # current
    subparsers.add_parser("current", help="Show the current migration revision.")

    # history
    subparsers.add_parser("history", help="Show full migration history.")

    # create-migration
    cm = subparsers.add_parser(
        "create-migration",
        help="Generate an autogenerated migration file.",
    )
    cm.add_argument(
        "-m",
        "--message",
        required=True,
        help="Short description of the schema change.",
    )

    # check
    subparsers.add_parser(
        "check",
        help="Verify the database schema is up to date (exits 1 if not).",
    )

    return parser


_COMMAND_MAP = {
    "migrate": cmd_migrate,
    "rollback": cmd_rollback,
    "downgrade": cmd_downgrade,
    "reset": cmd_reset,
    "seed": cmd_seed,
    "current": cmd_current,
    "history": cmd_history,
    "create-migration": cmd_create_migration,
    "check": cmd_check,
}


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    handler = _COMMAND_MAP.get(args.command)
    if handler is None:
        parser.print_help()
        sys.exit(1)
    try:
        handler(args)
    except SystemExit:
        raise
    except Exception as exc:
        logger.exception("Command '%s' failed: %s", args.command, exc)
        sys.exit(1)


if __name__ == "__main__":
    main()
